name: Notify parent repository as submodule

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Notify main repo
        if: ${{ github.event.pull_request.merged == true || github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GHCR_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/debeule/news-analytics-dock/dispatches \
          -d '{"event_type":"update"}'